### PR TITLE
Project Tic-tac-toe game Milestone 2

### PR DESCRIPTION
**Pull request by Zubenna**
## In this milestone, we did the following;
- Prompts for two different players
- Prompt for the player's name
- Displays current player name
- Specified symbol "X" or "Y" that each player can select.
- Displays the game board.
- Displays board after each player takes a turn to play.
- Exits game when there is a winner or game ends in a draw.

### CODE REVIEW

**Comment by Dandush03** [comment]
# Status: 🟠 Required Changes 🟠 
### Hey guys ! 👋 
### This project is missing some feature to meets this milestone specification. I will list then below
#### Behaviour
    - [ ] [OPTIONAL] game asks players for their names
    - [ ] [REQUIRED] game tells which player turn it is
    - [ ] [REQUIRED] game asks the player to select from available moves
    - [ ] [REQUIRED] game informs the player if the selected move is invalid
    - [ ] [REQUIRED] game displays board after the player move (So next  player will see witch moves he can play)
    - [ ] [REQUIRED] game informs player if the selected move is a winning move
    - [ ] [REQUIRED] game informs the player if the selected move is a draw move
    - [ ] [REQUIRED] game repeats all actions for the next player's move
But instead right now when running your code, I entered an infinite loop that I can only exit by hard closing the application.

## Please address all of this issue before submitting a new code review.

## Happy Coding 💻 

Daniel Laloush

**Comment by emiliocm9** [comment]
We started making some basic game logic to accomplish the required changes. We will start focusing on the game logic as soon as we start Milestone 3, and we will implement the logic for determining the winning status as well, but we have already done part of it.

**Comment by lekegitrepo** [comment]
#### Hi @Zubenna and @emiliocm9 :clap: :clap:
#### Good job. You still need to improve some aspect of your implementation, check my comment below :point_down:

- **_Terminate the game loop (in other words stop the game) when we have a winner or a draw._**

**_fix this and submit for review._**

### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by Zubenna** [comment]
This is the game simulation, full implementation will be in the next milestone

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

You can move on :+1: 
Good continuation :handshake: 

Mael FOSSO

**Pull request merged**
